apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dumbkv-monitor
  labels:
    app: dumbkv
spec:
  selector:
    matchLabels:
      app: dumbkv
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s